/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.northeastern.aziz.ui;

import edu.northeastern.aziz.Doctor.DoctorDirectory;
import edu.northeastern.aziz.Hospital.Hospital;
import edu.northeastern.aziz.Hospital.HospitalDirectory;
import edu.northeastern.aziz.Model.CityDirectory;
import edu.northeastern.aziz.Model.CommunityDirectory;
import edu.northeastern.aziz.Model.HouseDirectory;
import edu.northeastern.aziz.Patient.PatientDirectory;
import edu.northeastern.aziz.Persona.CommunityAdmin;
import edu.northeastern.aziz.Persona.CommunityAdminDirectory;
import edu.northeastern.aziz.Persona.HospitalAdmin;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author aziz
 */
public class AddCommunityAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommunityAdminJPanel
     */
    PatientDirectory patientDir;
    DoctorDirectory docDir;
    HospitalDirectory hospDir;
    CityDirectory cityDir;
    CommunityDirectory commDir;
    HouseDirectory houseDir;
    CommunityAdminDirectory commAdminDir;
    
    public AddCommunityAdminJPanel(CityDirectory cityDir, CommunityDirectory commDir, HouseDirectory houseDir, PatientDirectory patientDir, DoctorDirectory docDir, HospitalDirectory hospDir, CommunityAdminDirectory commAdminDir) {
        initComponents();
        this.patientDir = patientDir;
        this.cityDir = cityDir;
        this.commDir = commDir;
        this.houseDir = houseDir;
        this.hospDir = hospDir;
        this.docDir = docDir;
        this.commAdminDir = commAdminDir;
        
        
        // add hospitals in combobox
        DefaultComboBoxModel hospComboBox = new DefaultComboBoxModel();
        hospComboBox.addElement("Select");
        
        for (Hospital c : hospDir.getHospitalDirectory()) {
            hospComboBox.addElement(c.getHospitalName());
        }
        
        //comboBoxHosp.setModel(hospComboBox);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        comboBoxgender = new javax.swing.JComboBox<>();
        txtUsername = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtPhoneNo = new javax.swing.JTextField();
        lblPhoneNo = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Community Admin");

        lblName.setText("Name");

        comboBoxgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Other" }));

        lblUsername.setText("Username");

        lblEmail.setText("Email");

        lblPhoneNo.setText("Phone No");

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        lblAge.setText("Age");

        lblGender.setText("Gender");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblPass.setText("Password");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblName)
                                            .addGap(78, 78, 78)
                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblAge)
                                            .addGap(90, 90, 90)
                                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblGender)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblEmail)
                                                .addGap(80, 80, 80)
                                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblPhoneNo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(comboBoxgender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(114, 114, 114)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtUsername)
                                                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(lblUsername)
                                        .addComponent(lblPass))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(545, 545, 545)
                                .addComponent(btnCreate)))
                        .addGap(0, 560, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneNo))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(comboBoxgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPass))
                .addGap(119, 119, 119)
                .addComponent(btnCreate)
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        try {
        //Validation of Input Fields - START
        
        //Name
        String name = txtName.getText();
        if (name.length() <= 0) {
            JOptionPane.showMessageDialog(this, "Please enter a valid Name");
            return;
        }
        
        //Age
        String age = txtAge.getText();
        if (age.length() <= 0) {
            JOptionPane.showMessageDialog(this, "Please enter a valid Age");
            return;
        }
        if(age.length() > 0 && !age.matches("[0-9]+")){
            JOptionPane.showMessageDialog(this, "Age can contain only Numeric values");
            return;
        }
        
        //Email
        String email = txtEmail.getText();
        if (!isValidEmail(email)){
            JOptionPane.showMessageDialog(this, "Please enter a valid Email address");
            return;
        }
        //Phone Number
        String phoneNo = txtPhoneNo.getText();
        if (phoneNo.length() < 10 || phoneNo.length() > 10) {
            JOptionPane.showMessageDialog(this, "Please enter a valid 10 digits Phone Number");
            return;
        }
        if(phoneNo.length() > 0 && !phoneNo.matches("[0-9]+")){
            JOptionPane.showMessageDialog(this, "Please enter a valid 10 digits Phone Number");
            return;
        }
        //Gender 
        String gender = comboBoxgender.getSelectedItem().toString();
        if ("Select".equals(gender)) {
            JOptionPane.showMessageDialog(this, "Please select Gender");
            return;
        }
                
        //Username
        String userName = txtUsername.getText();
        if (userName.length() <= 0) {
            JOptionPane.showMessageDialog(this, "Please enter a valid Username");
            return;
        }
        
        //Password
        String pass = txtPass.getText();
        if (pass.length() <= 0) {
            JOptionPane.showMessageDialog(this, "Please enter a valid Password");
            return;
        }
        


        
     
        CommunityAdmin commAdmin = commAdminDir.addNewCommAdmin();

        commAdmin.setName(name);
        commAdmin.setAge(Short.parseShort(age));
        commAdmin.setEmail(email);
        commAdmin.setGender(gender);
        commAdmin.setPhoneNo(Long.parseLong(phoneNo));
        commAdmin.setUsername(userName);
        commAdmin.setPassword(pass);
        
        //JOptionPane.showMessageDialog(this, "New Patient record added"+ " U = "+ p.get(0).getUsername()+ " P = "+ p.get(0).getPassword());
        JOptionPane.showMessageDialog(this, "New Community Admin record added");
        
        txtName.setText("");
        txtAge.setText("");
        lblGender.setText("");
        txtUsername.setText("");
        txtPass.setText("");
        txtEmail.setText("");
        txtPhoneNo.setText("");
        comboBoxgender.setSelectedIndex(0); 
        
        }
        catch (Exception e){
            
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private boolean isValidEmail(String email) {
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+
                            "[a-zA-Z0-9_+&*-]+)*@" +
                            "(?:[a-zA-Z0-9-]+\\.)+[a-z" +
                            "A-Z]{2,7}$";
                              
        Pattern pat = Pattern.compile(emailRegex);
        if (email == null)
            return false;
        return pat.matcher(email).matches();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox<String> comboBoxgender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPhoneNo;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
